baseurl: "https://dritings.no"
title: "boozoholics"
members:
  - arcane
  - bronix
  - dodke
  - dominei
  - gus
  - kusma
  - leia
  - lug00ber
  - menace
  - quisten
  - raimo
  - sanders
  - slummy
  - waffle
  - xbit
  - zack
