baseurl: ""
title: "boozoholics"
members:
  - arcane
  - bronix
  - dodke
  - dominei
  - gus
  - kusma
  - leia
  - lug00ber
  - menace
  - nosfe
  - offwhite
  - quisten
  - raimo
  - sanders
  - slummy
  - spexzter
  - waffle
  - xbit
  - zack
